### ISSUE TITLE
Bouton suppression fond écran étrange 

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/mod-sign#3]
![image](https://user-images.githubusercontent.com/13015521/45263543-1bee5e00-b42b-11e8-9a2e-7808c6e8bd72.png)

J'ai supprimé mon fond d'écran préféré sans faire exprès ^^

**Comment by machine62** [comment]
le mode est a jour, il me semble l'avoir corrigé ce BUG .

**Comment by darknoon29** [comment]
Oui j'ai trouvé le commit. On peut fermer ce ticket :-)
