### ISSUE TITLE
Erreur dans le common.php

### ISSUE THREAD

**Issue by Cluster45** [OGSteam/mod-sign#5]
Il y a une petite erreur de code dans le fichier "common.php du mod "sign" 
La ligne que j'ai mise en commentaire affiche 2 fois la production de cristal sur les signatures. J'ai mis la ligne corrigée en dessous (testée sur mon Wampserver en local) ça corrige le problème).
-------------------------------------------------
// on prépare le retour (erreur 
	//$ress = array("M"=>$M,"C"=>$C,"D"=>$C)
	$ress = array("M"=>$M,"C"=>$C,"D"=>$D);
	$temp = array("heure" => 1 , "jour" => 24, "semaine" => 168, "mois" => 720); /// en nb d heure

**Comment by machine62** [comment]
corrigé
